[project]
name = "django-musicbrainz-connector"
description = "A Django app that connects to a replica of the MusicBrainz database."
version = "0.0.10"
dependencies = [
    "django>=5.2",
    "djangorestframework",
    "psycopg",
]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Marios Zindilis", email = "marios@zindilis.com" },
]

[project.urls]
homepage = "https://github.com/mneia-gr/django-musicbrainz-connector"
repository = "https://github.com/mneia-gr/django-musicbrainz-connector"
documentation = "https://django-musicbrainz-connector.readthedocs.io/"

[dependency-groups]
# Install test dependencies with `pip install --group test`. Requires pip version 25.1 or newer.
test = [
    "flake8",
    "flake8-pyproject",
    "black",
    "isort",
    "bandit",
    "django-upgrade",
    "pytest",
    "pytest-cov",
    "pytest-django",
    "coverage",
]
# Install build dependencies with `pip install --group test`. Requires pip version 25.1 or newer.
build = [
    "build"
]

[tool.flake8]
max-line-length = 120

[tool.black]
line-length = 120

[tool.isort]
multi_line_output = 3  # https://pycqa.github.io/isort/docs/configuration/options.html#multi-line-output
include_trailing_comma = true  # require trailing comma at the end of a list of imports in parentheses
line_length = 120  # https://pycqa.github.io/isort/docs/configuration/options.html#line-length

[tool.bandit]
assert_used = { skips = [ "*/test_*.py" ] } # Allow `assert` to be used in tests

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "django_musicbrainz_connector.tests.settings"
addopts = "-vv --cov-report term-missing --cov . --no-migrations"

[tool.coverage.run]
source = ["."]
omit = [
    "manage.py",
    "conftest.py",
    "django_musicbrainz_connector/migrations/*.py",
    "django_musicbrainz_connector/tests/*",
]

[tool.coverage.report]
show_missing = true
