[options]
tests_require =
    pytest >= 8.3.4
    pytest-django >= 4.9.0
    coverage >= 7.6.10

[options.extras_require]
test =
    flake8 >= 7.1.1
    black >= 24.10.0
    isort >= 5.13.2
    bandit >= 1.8.2

[flake8]
max-line-length=120

[coverage:run]
source = .
omit =
    manage.py
    setup.py
    conftest.py
    django_musicbrainz_connector/migrations/*.py
    django_musicbrainz_connector/tests/*

[coverage:report]
show_missing = true
